# Generated by Django 3.2.6 on 2021-11-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deaths', models.CharField(max_length=1000)),
                ('cases', models.CharField(max_length=1000)),
                ('recovered', models.CharField(max_length=1000)),
            ],
        ),
    ]
