# Generated by Django 3.2.6 on 2021-11-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='lastUpdated',
            field=models.DateField(auto_now=True),
        ),
    ]
